export const PLUGIN_NAME = 'page-design';
export const DEFAULT_LANGUAGE = 'zh-cn';
export {
  SUPPORT_COLUMN_TYPE,
  FORMULA_COLUMN_TYPES,
  STATIC_CELL_TYPE,
  IMAGE_TYPES,
  MULTIPLE_IMAGE_TYPES,
  DYNAMIC_CELL_TYPE,
  VIEW_TYPE,
  LINK_TABLE,
  TABLE_TYPES,
  PAGE_HEADER_FOOTER_TYPE,
  PAGE_HEADER_FOOTER_TYPES,
  PAGE_HEADER_FOOTER_WIDGET_TYPES,
} from './cell-constants';
export { IMAGE_QUALITY, PAGE_TYPE, PAGE_SIZE, LAYOUT_TYPE, ROW_TYPE, DEFAULT_PRINT_SETTINGS } from './print-constants';
export {
  BACKGROUND,
  DEFAULT_TABLE_HEADER_BACKGROUND_COLOR,
  FIT_MODE,
  FIT_MAP,
  HORIZONTAL_ALIGN,
  VERTICAL_ALIGN,
  IMAGE_DISPLAY_TYPE,
  FONT_WEIGHT,
  FONT,
  IMAGE_SIZING,
  IMAGE_SIZING_MAP,
  PROPERTIES_TRANSLATE_MAP,
  TABLE_ROW_HEIGHT_TYPE,
  TABLE_ROW_HEIGHT_LIST,
  TABLE_ROW_HEIGHT_VALUE_MAP,
  DISPLAY_TYPE,
  COMMON_DISPLAY_LABEL_CONFIG,
  COMMON_DISPLAY_TEXT_CONFIG
} from './properties-constants';
export { SCALING_RATIO } from './scale-constants';
