export const COMMON_FORM_COLUMN_TYPE = {
  COLUMN_NAME: 'COLUMN_NAME',
  COLUMN_TYPE: 'COLUMN_TYPE',
};

export const TEXT_FORM_COLUMN = {
  CUSTOM_REGULAR: 'CUSTOM_REGULAR',
};

export const NUMBER_FORM_COLUMN = {
  CUSTOM_CURRENCY: 'CUSTOM_CURRENCY',
};
