[pytest]
python_files=test_*.py tests.py
python_classes=Test* *Test
addopts = -s -v
DJANGO_SETTINGS_MODULE=seahub.test_settings
testpaths =
    tests/knowledge_base
    tests/tickets
    tests/utils
    tests/chats
    tests/connections
    tests/ai
    tests/search
    tests/notifications
    tests/portal
