import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CustomizeSelect } from '@/components';
import { gettext } from '@/constants';

import './index.css';

const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English' },
  { value: 'zh-cn', label: '中文' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
];

const LanguageSettings = ({
  value: oldValue = 'en',
  onChange,
}) => {
  const [value, setValue] = useState(oldValue);

  useEffect(() => {
    setValue(oldValue || 'en');
  }, [oldValue]);

  const selectedOption = useMemo(() => {
    return LANGUAGE_OPTIONS.find(option => option.value === value) || LANGUAGE_OPTIONS[0];
  }, [value]);

  const onValueChange = useCallback((newValue) => {
    setValue(newValue);
    onChange && onChange(newValue);
  }, [onChange]);

  return (
    <>
      <div className="language-settings-header text-truncate">{gettext('Language for AI summary')}</div>
      <div className="language-settings">
        <CustomizeSelect
          className="language-selector"
          value={selectedOption}
          options={LANGUAGE_OPTIONS}
          placeholder={gettext('Language for summary generated by AI')}
          onChange={onValueChange}
        />
      </div>
    </>
  );
};

export default LanguageSettings;
