PORTAL_EXTERNAL_CHAT_USER_RATE_LIMIT = 20
PORTAL_EXTERNAL_CHAT_USER_RATE_WINDOW = 10 * 60
PORTAL_EXTERNAL_CHAT_PROJECT_RATE_LIMIT = 100
PORTAL_EXTERNAL_CHAT_PROJECT_RATE_WINDOW = 60 * 60

PORTAL_ANON_CHAT_SESSION_DAILY_LIMIT = 20
PORTAL_ANON_CHAT_IP_DAILY_LIMIT = 50
PORTAL_ANON_CHAT_DAILY_TTL = 24 * 60 * 60

PORTAL_CHAT_DAILY_CREDIT_LIMIT_DEFAULT = 50
