from django.conf import settings


TICKET_DEFAULT_SUBSTATE_CACHE_TIMEOUT = getattr(settings, 'TICKET_DEFAULT_SUBSTATE_CACHE_TIMEOUT', 10 * 60)
TICKET_DEFAULT_SUBSTATE_CACHE_PREFIX =  getattr(settings, 'TICKET_DEFAULT_SUBSTATE_CACHE_PREFIX', 'TICKET_DEFAULT_SUBSTATE_')
