export const DEFAULT_PROJECT_ICON = 'haiwen-hash-fill';

export const PROJECT_ICON_LIST = [
  'haiwen-alarm-fill',
  'haiwen-book-bookmark-fill',
  'haiwen-book-ledger-fill',
  'haiwen-bug-fill',
  'haiwen-calendar-check-fill',
  'haiwen-calendar-dots-fill',
  'haiwen-chart-trend-fill',
  'haiwen-cooperation-fill',
  'haiwen-cube-fill',
  'haiwen-currency-dollar-fill',
  'haiwen-device-fill',
  'haiwen-film-fill',
  'haiwen-flask-fill',
  'haiwen-folder-user-fill',
  'haiwen-grid-menu',
  'haiwen-hash-fill',
  'haiwen-house-money-fill',
  'haiwen-list-bullets-fill',
  'haiwen-list-checks-fill',
  'haiwen-megaphone-fill',
  'haiwen-notebook-fill',
  'haiwen-pencil-ruler-fill',
  'haiwen-phone-chat-fill',
  'haiwen-presentation-chart-fill',
  'haiwen-store-fill',
  'haiwen-support-fill',
  'haiwen-team-chat-fill',
  'haiwen-user-list-fill',
  'haiwen-users-three-fill',
];

export const PROJECT_ICON_CATEGORIES = [
  {
    id: 'common',
    name: 'Common Icons',
    icons: [
      'haiwen-alarm-fill',
      'haiwen-book-bookmark-fill',
      'haiwen-book-ledger-fill',
      'haiwen-bug-fill',
      'haiwen-calendar-check-fill',
      'haiwen-calendar-dots-fill',
      'haiwen-chart-trend-fill',
      'haiwen-cooperation-fill',
      'haiwen-cube-fill',
      'haiwen-currency-dollar-fill',
      'haiwen-device-fill',
      'haiwen-film-fill',
      'haiwen-flask-fill',
      'haiwen-folder-user-fill',
      'haiwen-grid-menu',
      'haiwen-hash-fill',
      'haiwen-house-money-fill',
      'haiwen-list-bullets-fill',
      'haiwen-list-checks-fill',
      'haiwen-megaphone-fill',
      'haiwen-notebook-fill',
      'haiwen-pencil-ruler-fill',
      'haiwen-phone-chat-fill',
      'haiwen-presentation-chart-fill',
      'haiwen-store-fill',
      'haiwen-support-fill',
      'haiwen-team-chat-fill',
      'haiwen-user-list-fill',
      'haiwen-users-three-fill',
    ],
  },
  {
    id: 'system-devices',
    name: 'System & Devices Icons',
    icons: [
      'haiwen-address-book-fill',
      'haiwen-airplay-fill',
      'haiwen-archive-fill',
      'haiwen-asterisk-fill',
      'haiwen-barcode-fill',
      'haiwen-battery-charging-fill',
      'haiwen-bell-simple-fill',
      'haiwen-bluetooth-fill',
      'haiwen-book-open-text-fill',
      'haiwen-book-open-user-fill',
      'haiwen-bookmarks-fill',
      'haiwen-books-fill',
      'haiwen-bounding-box-fill',
      'haiwen-box-arrow-down-fill',
      'haiwen-box-arrow-up-fill',
      'haiwen-browsers-fill',
      'haiwen-calculator-fill',
      'haiwen-certificate-fill',
      'haiwen-chalkboard-simple-fill',
      'haiwen-chart-bar-fill',
      'haiwen-chart-bar-horizontal-fill',
      'haiwen-chart-donut-fill',
      'haiwen-chart-line-fill',
      'haiwen-chart-pie-slice-fill',
      'haiwen-chart-polar-fill',
      'haiwen-chart-scatter-fill',
      'haiwen-chat-text-fill',
      'haiwen-check-square-fill',
      'haiwen-clipboard-text-fill',
      'haiwen-clock-fill',
      'haiwen-closed-captioning-fill',
      'haiwen-cloud-fill',
      'haiwen-code-fill',
      'haiwen-compass-fill',
      'haiwen-contactless-payment-fill',
      'haiwen-copyright-fill',
      'haiwen-crop-fill',
      'haiwen-crosshair-simple-fill',
      'haiwen-cube-focus-fill',
      'haiwen-database-fill',
      'haiwen-desktop-fill',
      'haiwen-desktop-tower-fill',
      'haiwen-device-mobile-fill',
      'haiwen-devices-fill',
      'haiwen-disc-fill',
      'haiwen-envelope-fill',
      'haiwen-eraser-fill',
      'haiwen-exam-fill',
      'haiwen-file-archive-fill',
      'haiwen-file-fill',
      'haiwen-fingerprint-fill',
      'haiwen-flag-fill',
      'haiwen-floppy-disk-back-fill',
      'haiwen-folder-fill',
      'haiwen-function-fill',
      'haiwen-gif-fill',
      'haiwen-graphics-card-fill',
      'haiwen-headset-fill',
      'haiwen-high-definition-fill',
      'haiwen-hourglass-fill',
      'haiwen-house-line-fill',
      'haiwen-identification-badge-fill',
      'haiwen-identification-card-fill',
      'haiwen-image-fill',
      'haiwen-infinity-fill',
      'haiwen-kanban-fill',
      'haiwen-key-fill',
      'haiwen-keyhole-fill',
      'haiwen-laptop-fill',
      'haiwen-lightbulb-fill',
      'haiwen-link-fill',
      'haiwen-lock-simple-fill',
      'haiwen-log-fill',
      'haiwen-magic-wand-fill',
      'haiwen-magnet-fill',
      'haiwen-magnifying-glass-fill',
      'haiwen-mailbox-fill',
      'haiwen-map-pin-line-fill',
      'haiwen-medal-fill',
      'haiwen-megaphone-simple-fill',
      'haiwen-memory-fill',
      'haiwen-microphone-fill',
      'haiwen-paper-plane-tilt-fill',
      'haiwen-paperclip-fill',
      'haiwen-password-fill',
      'haiwen-percent-fill',
      'haiwen-prescription-fill',
      'haiwen-printer-fill',
      'haiwen-qr-code-fill',
      'haiwen-receipt-fill',
      'haiwen-robot-fill',
      'haiwen-screwdriver-fill',
      'haiwen-scribble-fill',
      'haiwen-security-camera-fill',
      'haiwen-shield-check-fill',
      'haiwen-shield-warning-fill',
      'haiwen-signature-fill',
      'haiwen-speaker-high-fill',
      'haiwen-stack-fill',
      'haiwen-standard-definition-fill',
      'haiwen-table-fill',
      'haiwen-tag-fill',
      'haiwen-toolbox-fill',
      'haiwen-trademark-fill',
      'haiwen-trademark-registered-fill',
      'haiwen-translate-fill',
      'haiwen-trophy-fill',
      'haiwen-user-fill',
      'haiwen-users-fill',
      'haiwen-vault-fill',
    ],
  },
  {
    id: 'transport-location',
    name: 'Transport & Location Icons',
    icons: [
      'haiwen-airplane-tilt-fill',
      'haiwen-boat-fill',
      'haiwen-bridge-fill',
      'haiwen-building-office-fill',
      'haiwen-bus-fill',
      'haiwen-cable-car-fill',
      'haiwen-cactus-fill',
      'haiwen-camera-fill',
      'haiwen-car-fill',
      'haiwen-charging-station-fill',
      'haiwen-lighthouse-fill',
      'haiwen-mountains-fill',
      'haiwen-road-horizon-fill',
      'haiwen-subway-fill',
      'haiwen-traffic-cone-fill',
      'haiwen-traffic-sign-fill',
      'haiwen-traffic-signal-fill',
    ],
  },
  {
    id: 'entertainment-games',
    name: 'Entertainment & Games Icons',
    icons: [
      'haiwen-alien-fill',
      'haiwen-bomb-fill',
      'haiwen-bone-fill',
      'haiwen-cassette-tape-fill',
      'haiwen-checkerboard-fill',
      'haiwen-film-reel-fill',
      'haiwen-game-controller-fill',
      'haiwen-ghost-fill',
      'haiwen-guitar-fill',
      'haiwen-music-notes-fill',
      'haiwen-newspaper-fill',
      'haiwen-video-fill',
      'haiwen-vinyl-record-fill',
      'haiwen-virtual-reality-fill',
    ],
  },
  {
    id: 'medical-health',
    name: 'Medical & Health Icons',
    icons: [
      'haiwen-ambulance-fill',
      'haiwen-asclepius-fill',
      'haiwen-barbell-fill',
      'haiwen-basketball-fill',
      'haiwen-boules-fill',
      'haiwen-first-aid-kit-fill',
      'haiwen-hospital-fill',
      'haiwen-pill-fill',
    ],
  },
  {
    id: 'design-geometry',
    name: 'Design & Geometry Icons',
    icons: [
      'haiwen-angle-fill',
      'haiwen-aperture-fill',
      'haiwen-bezier-curve-fill',
      'haiwen-eyedropper-sample-fill',
      'haiwen-paint-bucket-fill',
      'haiwen-palette-fill',
      'haiwen-pen-nib-fill',
      'haiwen-shapes-fill',
      'haiwen-spiral-fill',
      'haiwen-swatches-fill',
    ],
  },
  {
    id: 'objects-daily-life',
    name: 'Objects & Daily Life Icons',
    icons: [
      'haiwen-armchair-fill',
      'haiwen-article-ny-times-fill',
      'haiwen-baby-fill',
      'haiwen-balloon-fill',
      'haiwen-barricade-fill',
      'haiwen-basket-fill',
      'haiwen-beanie-fill',
      'haiwen-beer-stein-fill',
      'haiwen-book-fill',
      'haiwen-boot-fill',
      'haiwen-bowl-steam-fill',
      'haiwen-bread-fill',
      'haiwen-broom-fill',
      'haiwen-cake-fill',
      'haiwen-call-bell-fill',
      'haiwen-carrot-fill',
      'haiwen-chair-fill',
      'haiwen-cheers-fill',
      'haiwen-cherries-fill',
      'haiwen-coffee-fill',
      'haiwen-confetti-fill',
      'haiwen-cookie-fill',
      'haiwen-cooking-pot-fill',
      'haiwen-crown-simple-fill',
      'haiwen-face-mask-fill',
      'haiwen-flashlight-fill',
      'haiwen-fork-knife-fill',
      'haiwen-gift-fill',
      'haiwen-hamburger-fill',
      'haiwen-high-heel-fill',
      'haiwen-ice-cream-fill',
      'haiwen-phone-call-fill',
      'haiwen-pinwheel-fill',
      'haiwen-shopping-cart-fill',
      'haiwen-smiley-fill',
      'haiwen-storefront-fill',
      'haiwen-suitcase-rolling-fill',
      'haiwen-tent-fill',
      'haiwen-umbrella-simple-fill',
      'haiwen-webcam-fill',
      'haiwen-yarn-fill',
    ],
  },
  {
    id: 'nature-science',
    name: 'Nature & Science Icons',
    icons: [
      'haiwen-atom-fill',
      'haiwen-binary-fill',
      'haiwen-binoculars-fill',
      'haiwen-biohazard-fill',
      'haiwen-bird-fill',
      'haiwen-blueprint-fill',
      'haiwen-brain-fill',
      'haiwen-broadcast-fill',
      'haiwen-butterfly-fill',
      'haiwen-cat-fill',
      'haiwen-cell-tower-fill',
      'haiwen-circuitry-fill',
      'haiwen-cow-fill',
      'haiwen-cpu-fill',
      'haiwen-dna-fill',
      'haiwen-dog-fill',
      'haiwen-drop-fill',
      'haiwen-ear-fill',
      'haiwen-fallout-shelter-fill',
      'haiwen-fan-fill',
      'haiwen-farm-fill',
      'haiwen-fire-fill',
      'haiwen-footprints-fill',
      'haiwen-globe-hemisphere-east-fill',
      'haiwen-graduation-cap-fill',
      'haiwen-grains-fill',
      'haiwen-head-circuit-fill',
      'haiwen-hurricane-fill',
      'haiwen-lightning-fill',
      'haiwen-math-operations-fill',
      'haiwen-meteor-fill',
      'haiwen-microscope-fill',
      'haiwen-person-fill',
      'haiwen-pi-fill',
      'haiwen-planet-fill',
      'haiwen-plug-charging-fill',
      'haiwen-potted-plant-fill',
      'haiwen-radioactive-fill',
      'haiwen-rocket-launch-fill',
      'haiwen-rss-fill',
      'haiwen-skull-fill',
      'haiwen-snowflake-fill',
      'haiwen-solar-panel-fill',
      'haiwen-sparkle-fill',
      'haiwen-sun-fill',
      'haiwen-thermometer-fill',
      'haiwen-tooth-fill',
      'haiwen-tornado-fill',
      'haiwen-tree-evergreen-fill',
      'haiwen-virus-fill',
      'haiwen-waveform-fill',
    ],
  },
  {
    id: 'business-finance',
    name: 'Business & Finance Icons',
    icons: [
      'haiwen-bag-fill',
      'haiwen-bank-fill',
      'haiwen-bulldozer-fill',
      'haiwen-cardholder-fill',
      'haiwen-coins-fill',
      'haiwen-crane-tower-fill',
      'haiwen-credit-card-fill',
      'haiwen-currency-btc-fill',
      'haiwen-currency-cny-fill',
      'haiwen-currency-eur-fill',
      'haiwen-currency-gbp-fill',
      'haiwen-currency-jpy-fill',
      'haiwen-currency-krw-fill',
      'haiwen-engine-fill',
      'haiwen-factory-fill',
      'haiwen-garage-fill',
      'haiwen-hard-hat-fill',
      'haiwen-nuclear-plant-fill',
      'haiwen-piggy-bank-fill',
      'haiwen-pipe-fill',
      'haiwen-wallet-fill',
      'haiwen-warehouse-fill',
    ],
  },
];

export const PROJECT_ICON_ALL_LIST = PROJECT_ICON_CATEGORIES.reduce((icons, category) => {
  return icons.concat(category.icons);
}, []);

export const DEFAULT_COLOR = '#FF8000';

export const PROJECT_ICON_COLORS = [
  '#FF8000',
  '#FDA900',
  '#F5475C',
  '#EC00B1',
  '#7E35F8',
  '#B830D7',
  '#44D243',
  '#28C38D',
  '#00B3EE',
  '#00B7B5',
  '#1588FC',
  '#574F49',
];

export const DEFAULT_MARKER_STYLE = { type: 'check', color: '#1DDD1D' };
