export const PROJECT_ICON_LIST = [
  'icon-worksheet',
  'icon-task-management',
  'icon-software-test-management',
  'icon-design-assignment',
  'icon-video-production',
  'icon-market-analysis',
  'icon-data-analysis',
  'icon-product-knowledge-base',
  'icon-asset-management',
  'icon-financial-information-record',
  'icon-dollar',
  'icon-company-inventory',
  'icon-customer-inquiry',
  'icon-customer-list',
  'icon-product-list',
  'icon-store-address',
  'icon-leave-record',
  'icon-administrative-matters-calendar',
  'icon-customer-relationship',
  'icon-teachers-list',
  'icon-book-library',
  'icon-server-management',
  'icon-time-management',
  'icon-work-log',
  'icon-online-promotion',
  'icon-research',
  'icon-user-interview',
  'icon-client-review',
  'icon-club-members',
];

export const DEFAULT_COLOR = '#FF8000';

export const PROJECT_ICON_COLORS = [
  '#FF8000',
  '#FDA900',
  '#F5475C',
  '#EC00B1',
  '#7E35F8',
  '#B830D7',
  '#44D243',
  '#28C38D',
  '#00B3EE',
  '#00B7B5',
  '#1588FC',
  '#574F49',
];

export const DEFAULT_MARKER_STYLE = { type: 'check', color: '#1DDD1D' };
