from django.conf import settings

EASY_DL_TOKEN_TIMEOUT = getattr(settings, 'EASY_DL_TOKEN_TIMEOUT', 24*60*60)
EASY_DL_TOKEN_CACHE_PREFIX = getattr(settings, 'EASY_DL_TOKEN_CACHE_PREFIX', 'EASY_DL_TOKEN_')
DTABLE_SHARE_QUOTA = getattr(settings, 'DTABLE_SHARE_QUOTA', 200)
DTABLE_RELATED_USERS_PER_PAGE = getattr(settings, 'DTABLE_RELATED_USERS_PER_PAGE', 300)
DTABLE_APP_USERS_PER_PAGE = getattr(settings, 'DTABLE_APP_USERS_PER_PAGE', 100)
DTABLE_EXTERNAL_LINK_QUOTA = getattr(settings, 'DTABLE_EXTERNAL_LINK_QUOTA', 100)
DTABLE_EXTERNAL_VIEW_LINK_QUOTA = getattr(settings, 'DTABLE_EXTERNAL_VIEW_LINK_QUOTA', 100)
DTABLE_EXTERNAL_APP_QUOTA = getattr(settings, 'DTABLE_EXTERNAL_APP_QUOTA', 100)
DTABLE_FORM_QUOTA = getattr(settings, 'DTABLE_FORM_QUOTA', 100)
DTABLE_SHARE_PERMISSION_QUOTA = getattr(settings, 'DTABLE_SHARE_PERMISSION_QUOTA', 100)
