# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0006_dtablerowshares'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaces',
            name='org_id',
            field=models.IntegerField(default=-1),
        ),
    ]
