# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0007_workspaces_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTableForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('workspace_id', models.IntegerField(db_index=True)),
                ('dtable_uuid', models.CharField(db_index=True, max_length=36)),
                ('form_id', models.CharField(max_length=36)),
                ('form_config', models.TextField(null=True)),
                ('token', models.CharField(max_length=36, unique=True)),
            ],
            options={
                'db_table': 'dtable_forms',
            },
        ),
        migrations.DeleteModel(
            name='DTableFormLinks',
        ),
        migrations.AlterUniqueTogether(
            name='dtableforms',
            unique_together=set([('dtable_uuid', 'form_id')]),
        ),
    ]
