# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0008_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTablePlugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(null=True)),
                ('last_modified', models.DateTimeField()),
                ('added_by', models.CharField(max_length=255)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('dtable', models.ForeignKey(db_column='dtable_id', on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'dtable_plugin',
            },
        ),
        migrations.CreateModel(
            name='DTableSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtable_uuid', models.CharField(db_index=True, max_length=36)),
                ('dtable_name', models.CharField(max_length=255)),
                ('commit_id', models.CharField(max_length=40, unique=True)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dtable_snapshot',
            },
        ),
        migrations.CreateModel(
            name='SeafileConnectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seafile_url', models.CharField(max_length=255)),
                ('repo_api_token', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('dtable', models.ForeignKey(db_column='dtable_id', on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'dtable_seafile_connectors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='seafileconnectors',
            unique_together=set([('dtable', 'repo_api_token')]),
        ),
    ]
