# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-08 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0011_common_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTableFormShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(db_index=True)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='dtable.DTableForms')),
            ],
            options={
                'db_table': 'dtable_form_share',
            },
        ),
        migrations.AddField(
            model_name='dtableforms',
            name='share_type',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('login_users', 'Login_Users'), ('shared_groups', 'Shared_Groups')], default='anonymous', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dtableformshare',
            unique_together=set([('form', 'group_id')]),
        ),
    ]
