# Copyright (c) 2012-2016 Seafile Ltd.
TEXT = 'Text'
IMAGE = 'Image'
DOCUMENT = 'Document'
PDF = 'PDF'
MARKDOWN = 'Markdown'
VIDEO = 'Video'
AUDIO = 'Audio'
SPREADSHEET = 'SpreadSheet'
DRAW = 'Draw'
XMIND = 'XMind'
CDOC = 'cdoc'
SEADOC = 'SDoc'
