#!/usr/bin/env python3
"""Delete the original Seadb bases after Base ID replacement."""

import argparse
import json
import logging
import sys
import os
from pathlib import Path
from typing import Any


sys.path.append('/opt/seaticket/seaqa-web')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'seahub.settings')
import django

django.setup()
from seahub.project.seadb_api import SeaDBAPI


logger = logging.getLogger(__name__)


def load_state(state_file: Path) -> dict[str, dict[str, Any]]:
    try:
        data = json.loads(state_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"Failed to read state file {state_file}: {exc}") from exc

    if not isinstance(data, dict):
        raise RuntimeError("The state file must be a JSON object.")

    for old_base_id, item in data.items():
        if not isinstance(old_base_id, str) or not isinstance(item, dict):
            raise RuntimeError("The state file contains an invalid Base entry.")

    return data


def write_state(state: dict[str, dict[str, Any]], state_file: Path) -> None:
    state_file.parent.mkdir(parents=True, exist_ok=True)
    temporary_file = state_file.with_suffix(f"{state_file.suffix}.tmp")
    temporary_file.write_text(
        json.dumps(state, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary_file.replace(state_file)


def get_deletable_bases(
    state: dict[str, dict[str, Any]],
) -> list[tuple[str, dict[str, Any]]]:
    deletable: list[tuple[str, dict[str, Any]]] = []
    for old_base_id, item in state.items():
        status = item.get("status")
        if status == "deleted":
            logger.info("Skipping already deleted temporary Base for %s.", old_base_id)
            continue
        if status != "completed":
            logger.warning(
                "Skipping Base %s because ID replacement is not complete; status: %s.",
                old_base_id,
                status,
            )
            continue

        temporary_base_id = item.get("temporary_base_id")
        if not isinstance(temporary_base_id, str) or not temporary_base_id:
            logger.error(
                "Skipping Base %s because temporary_base_id is missing.",
                old_base_id,
            )
            continue

        deletable.append((old_base_id, item))
    return deletable


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        stream=sys.stdout,
        force=True,
    )
    parser = argparse.ArgumentParser(
        description="Delete original Seadb bases after Base ID replacement."
    )
    parser.add_argument(
        "--mapping-file",
        type=Path,
        required=True,
        help="State file generated by replace_base_ids.py",
    )
    parser.add_argument(
        "--confirm",
        action="store_true",
        help="Actually delete the temporary Bases; omit for preview only",
    )
    args = parser.parse_args()

    try:
        state = load_state(args.mapping_file)
        deletable = get_deletable_bases(state)
    except RuntimeError as exc:
        logger.error("Failed to prepare Base deletion: %s", exc, exc_info=True)
        return 1

    if not deletable:
        logger.info("No completed temporary Bases are pending deletion.")
        return 0

    if not args.confirm:
        logger.warning(
            "Preview only. %d temporary Base(s) would be deleted. "
            "Use --confirm to perform deletion.",
            len(deletable),
        )
        for old_base_id, item in deletable:
            logger.info(
                "Would delete temporary Base %s, originally belonging to Base %s.",
                item["temporary_base_id"],
                old_base_id,
            )
        return 0

    try:
        seadb_api = SeaDBAPI()
    except Exception as exc:
        logger.error("Failed to initialize SeaDB API: %s", exc, exc_info=True)
        return 1

    failed_base_ids: list[str] = []
    for old_base_id, item in deletable:
        temporary_base_id = item["temporary_base_id"]
        logger.info(
            "Deleting temporary Base %s for original Base %s.",
            temporary_base_id,
            old_base_id,
        )
        try:
            seadb_api.delete_base(temporary_base_id)
            item["status"] = "deleted"
            item["deleted_base_id"] = temporary_base_id
            write_state(state, args.mapping_file)
            logger.info("Deleted temporary Base %s.", temporary_base_id)
        except Exception as exc:
            failed_base_ids.append(old_base_id)
            logger.error(
                "Failed to delete temporary Base %s for original Base %s: %s",
                temporary_base_id,
                old_base_id,
                exc,
                exc_info=True,
            )

    try:
        write_state(state, args.mapping_file)
    except OSError as exc:
        logger.error("Failed to save deletion state: %s", exc, exc_info=True)
        return 1

    if failed_base_ids:
        logger.error(
            "%d Base deletion(s) failed: %s",
            len(failed_base_ids),
            ", ".join(failed_base_ids),
        )
        return 1

    logger.info("Successfully deleted %d temporary Base(s).", len(deletable))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
