from django.http import HttpResponseRedirect
from seahub.api2.authentication import AuthenticationFailed
from seahub.api2.models import Token
from seahub.auth import REDIRECT_FIELD_NAME
from seahub.auth import login as auth_login
from seahub.utils import render_error
from seahub.settings import SITE_ROOT
from seahub.base.accounts import User
from seahub.base.accounts import AuthBackend


def mobile_login(request):

    """
    headers from android app such as
    "X-SEATABLE-MOBILE-AUTH: asd410d592f59efc64410bbf4ee7602eb6854dd7"
    the token is generated by login in by username and password
    """

    header_key = "HTTP_X_SEATABLE_MOBILE_AUTH"
    login_token = request.META.get(header_key, '')
    if not login_token:
        return render_error(request, 'token invalid.')

    try:
        token = Token.objects.get(key=login_token)
    except Token.DoesNotExist:
        raise AuthenticationFailed('Invalid token')

    try:
        user = User.objects.get(email=token.user)
    except User.DoesNotExist:
        raise AuthenticationFailed('User inactive or deleted')

    user.backend = AuthBackend.__module__ + ".AuthBackend"

    auth_login(request, user, mobile_login=True)

    redirect_to = request.GET.get(REDIRECT_FIELD_NAME, SITE_ROOT)
    return HttpResponseRedirect(redirect_to)
