name: SeaTable Dist CI

on:
  push:
    branches:
      - master
      - "2.4"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: apt install
        run: |
          sudo apt-get update --fix-missing || true
          sudo apt-get install -y gettext python3-dev libsasl2-dev libldap2-dev gcc

      - name: Build dist branch
        run: |
          cd $GITHUB_WORKSPACE/tests/ 
          chmod +x github_actions_dist.sh 
          ./github_actions_dist.sh
